* Use an editor to update the container_variables.txt file for your environment
* Source the container_variables.txt file and create the 389-ds data directory: `. container_variables.txt && mkdir $DATA_DIR`

NOTE: Sourcing the container_variables.txt file before each command ensures the correct variables are available for each command invocation

* Run the container:
----
. container_variables.txt && sudo podman run -d \
	-p 389:389 \
	-p 636:636 \
	-e INSTANCE_NAME=$INSTANCE_NAME \
	-e ROOT_DN=$ROOT_DN \
	-e ROOT_PASSWORD=$ROOT_PASSWORD \
	-e SUFFIX=$SUFFIX \
	-v $DATA_DIR:/data \
	--name $CONTAINER_NAME registry.suse.com/caasp/v4/389-ds:1.4.0
----

* Install LDAP client tools on a system that can access the LDAP server (the local system if INSTANCE_NAME is localhost): `sudo zypper -n install openldap2-client`

* Run a test search: `. container_variables.txt && ldapsearch -x -H ldap://localhost -b $SUFFIX -D "$ROOT_DN" -w $ROOT_PASSWORD`

NOTE: This section of the administration guide contains example for managing OU's, users, and groups: https://documentation.suse.com/suse-caasp/4.0.2/single-html/caasp-admin/#_adding_a_new_organizational_unit
 
 
.Add a new Organizational Unit:
* Create the update file(s) and place them in the updates-processing directory: 
----
while : ; do \
read -p "Enter new OU name (or Ctrl+c to end): " OU_NAME; \
echo ""; \
LDIF_UPDATE_FILE=add_ou_`date +"%d.%b.%Y.%H.%M.%S"`.ldif; \
cp -p add_ou_template.ldif updates-processing/$LDIF_UPDATE_FILE; \
. container_variables.txt && \
sed -i "s/OU_NAME/$OU_NAME/; \
s/SUFFIX/$SUFFIX/" updates-processing/$LDIF_UPDATE_FILE; \
done
----
* Continue with more updates or move on to the "Apply all of the update file(s) in the updates-proccessing directory" section

.Delete an Organizational Unit:
* Create the update file(s) and place them in the updates-processing directory: 
----
while : ; do \
read -p "Enter name of OU to delete (or Ctrl+c to end): " OU_NAME; \
echo ""; \
LDIF_UPDATE_FILE=delete_ou_`date +"%d.%b.%Y.%H.%M.%S"`.ldif; \
cp -p delete_ou_template.ldif updates-processing/$LDIF_UPDATE_FILE; \
. container_variables.txt && \
sed -i "s/OU_NAME/$OU_NAME/; \
s/SUFFIX/$SUFFIX/" updates-processing/$LDIF_UPDATE_FILE; \
done
----
* Continue with more updates or move on to the "Apply all of the update file(s) in the updates-proccessing directory" section

.Add a new Group:
* Create the update file(s) and place them in the updates-processing directory: 
----
while : ; do \
read -p "Enter new Group name (or Ctrl+c to end): " GROUP_NAME; \
read -p "Enter the existing OU to create the group in: " OU_NAME; \
echo ""; \
LDIF_UPDATE_FILE=add_group_`date +"%d.%b.%Y.%H.%M.%S"`.ldif; \
cp -p add_group_template.ldif updates-processing/$LDIF_UPDATE_FILE; \
. container_variables.txt && \
sed -i "s/GROUP_NAME/$GROUP_NAME/; \
s/OU_NAME/$OU_NAME/; \
s/SUFFIX/$SUFFIX/" updates-processing/$LDIF_UPDATE_FILE; \
done
----
* Continue with more updates or move on to the "Apply all of the update file(s) in the updates-proccessing directory" section

.Delete a Group:
* Create the update file(s) and place them in the updates-processing directory: 
----
while : ; do \
read -p "Enter name of Group to delete (or Ctrl+c to end): " GROUP_NAME; \
read -p "Enter the OU that contains the group to delete: " OU_NAME; \ 
echo ""; \
LDIF_UPDATE_FILE=delete_group_`date +"%d.%b.%Y.%H.%M.%S"`.ldif; \
cp -p delete_group_template.ldif updates-processing/$LDIF_UPDATE_FILE; \
. container_variables.txt && \
sed -i "s/GROUP_NAME/$GROUP_NAME/; \
s/OU_NAME/$OU_NAME/; \
s/SUFFIX/$SUFFIX/" updates-processing/$LDIF_UPDATE_FILE; \
done
----
* Continue with more updates or move on to the "Apply all of the update file(s) in the updates-proccessing directory" section

.Add a new User:
* Create the update file(s) and place them in the updates-processing directory: 
----
while : ; do \
read -p "Enter new User login name (or Ctrl+c to end): " USERID; \
read -p "Enter the existing OU to create the user in: " OU_NAME; \
read -p "Enter the SSHA hash of the user's password (if needed, use: http://projects.marsching.org/weave4j/util/genpassword.phpO: " PASSWORD_HASH; \
read -p "Enter new User's first name: " FIRST_NAME; \
read -p "Enter new User's last name: " SURNAME; \
read -p "Enter new User's full name: " FULL_NAME; \
read -p "Enter new User's email address: " EMAIL_ADDRESS; \
echo ""; \
LDIF_UPDATE_FILE=add_user_`date +"%d.%b.%Y.%H.%M.%S"`.ldif; \
cp -p add_user_template.ldif updates-processing/$LDIF_UPDATE_FILE; \
. container_variables.txt && \
sed -i "s/USERID/$USERID/; \
s/OU_NAME/$OU_NAME/; \
s/SUFFIX/$SUFFIX/; \
s/PASSWORD_HASH/$PASSWORD_HASH/; \
s/FIRST_NAME/$FIRST_NAME/; \
s/SURNAME/$SURNAME/; \
s/FULL_NAME/$FULL_NAME/; \
s/EMAIL_ADDRESS/$EMAIL_ADDRESS/" updates-processing/$LDIF_UPDATE_FILE; \
done
----
* Continue with more updates or move on to the "Apply all of the update file(s) in the updates-proccessing directory" section

.Apply all of the update file(s) in the updates-proccessing directory: 
* Review all of the files in the updates-proccessing directory before proceeding
* Additional .ldif files can be added for batch processing if they fit the schema of the LDAP database
----
for EACH_UPDATE in `ls -1 updates-processing/`; do \
. container_variables.txt && \
ldapmodify -v -H $LDAP_PROTOCOL://$LDAP_SERVER_FQDN$LDAP_SERVER_PORT -D "$BIND_DN" -f updates-processing/$EACH_UPDATE -w $ROOT_PASSWORD && \
mv updates-processing/$EACH_UPDATE updates-completed/; \ # Need to update the date when moving to the completed directory
done
----




// vim: set syntax=asciidoc:

