#### This is a very simple implementation of the containerized 389-ds LDAP server 
#### It is meant to run on openSUSE15.0 or SLES15 and higher

NOTE: Tools to search and update the server after creatation can be found at: https://github.com/alexarnoldy/389-ds-LDAP-data-tools

* (Optional) Create a directory to contain this 389-ds LDAP server container and the data tools: `mkdir -p ~/389-ds-ldap-server && cd $_`
* Clone this repository: `git clone git@github.com:alexarnoldy/389-ds-LDAP-server-container.git && cd 389-ds-LDAP-server-container`
* Use an editor to update the container_variables.txt file to fit your environment
 
.Create and run the server container
* Source the container_variables.txt file and create the LDAP server data directory: `source container_variables.txt && mkdir $DATA_DIR`

NOTE: Sourcing the container_variables.txt file before each command ensures the correct variables are available for each command invocation

* Run the container:
----
source container_variables.txt && sudo podman run -d \
	-p 389:389 \
	-p 636:636 \
	-e INSTANCE_NAME=$INSTANCE_NAME \
	-e ROOT_DN=$ROOT_DN \
	-e ROOT_PASSWORD=$ROOT_PASSWORD \
	-e SUFFIX=$SUFFIX \
	-v $DATA_DIR:/data \
	--name $CONTAINER_NAME registry.suse.com/caasp/v4/389-ds:1.4.0
----

* Verify the container is running and the host is listening on port 389:
----
sudo podman ps -a
ss -npr --listening | grep 389
----

.(Optional) Run a test search on the server container
* Install LDAP client tools on a system that can access the LDAP server (the local system if INSTANCE_NAME is localhost): `sudo zypper -n install openldap2-client`

* Run a test search: `source container_variables.txt && ldapsearch -x -H ldap://localhost -b $SUFFIX -D "$ROOT_DN" -w $ROOT_PASSWORD`

* (Optional) Add the tools to search and update the server after creatation from: https://github.com/alexarnoldy/389-ds-LDAP-data-tools

// vim: set syntax=asciidoc:

